### ISSUE TITLE
Broken link for performance guide

### ISSUE THREAD

**Issue by pennychase** [reubenharry/haskell-docs#60]
The link to the performance guide in Resources>Overview is broken. It’s now at https://haskell.foundation/hs-opt-handbook.github.io/

**Comment by reubenharry** [comment]
Thanks so much! Now fixed! Note that you can propose edits directly with the edit button on the top right of each page.

**Comment by pennychase** [comment]
HI Reuben. I just forked the repo so can now do pull requests. Before making a PR, just wanted to ask a couple of questions.  First, since the Books section is only a section, would you want to add a link to Travis Cardwell's comprehensive list? Second, would it be ok to add an additional book or two (I really like Rebecca Skinner's Effective Haskell)? And if so, is your preference for the Amazon link or for the publisher web site (Pragmatic has the full table of contents, pdf excerpts, and code)?

**Comment by reubenharry** [comment]
Thanks for asking! I'm trying to avoid being comprehensive, and instead giving opinionated choices (see "less > more" here: https://github.com/reubenharry/haskell-docs/blob/main/Contributing.md). I also try to only mention free resources (in the interest of miminizing effort/commitment required for a newcomer) so this is why I didn't include non-free books. But that said, I'd be in favour of adding Effective Haskell (the publisher web site link) if you think it's a worthwhile book for beginners/intermediates. You could add it under a "Paid Resources" section, or similar.

(Also note that for quick changes, you don't even need to fork, you can just make PRs online (with the edit button as mentioned above). But of course for anything substantial, forking is the way.)
