### ISSUE TITLE
"Edit this page" link is broken

### ISSUE THREAD

**Issue by cdsmith** [reubenharry/haskell-docs#8]
At the top of each page is an edit icon with the title "Edit this page".  However, clicking on it leads to a 404 from GitHub, on a URL like `https://github.com/reubenharry/haskell-docs/edit/master/docs/index.md`.

**Comment by reubenharry** [comment]
Ah, was just about to open this issue, thanks! The relevant `MkDocs Material` doc is https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/#repository-icon, but I don't yet know how to fix. There's a master vs main issue, and also a docs vs docs/docs issue.

**Comment by reubenharry** [comment]
Fixed.
